### ISSUE TITLE
Tracking issue for E2E tests

### ISSUE THREAD

**Issue by tdelabro** [keep-starknet-strange/madara#904]
Currently, our integration tests are written in JS and we struggle to maintain them. We want to move over to rust.

# Working branch
In the first time of developing this test suite, there will be a lot of changes, from many different contributors at the same time.
We don't want to disrupt the main branch flow until we have something robust to merge. Therefore, in a first time, we will be working on this branch: https://github.com/keep-starknet-strange/madara/tree/feature/e2e-rust-tests.
All contributors' PR should be merged in this one.

# Roadmap:
- [x] Create a `test/` folder on the workspace root
- [x] add it in the `[test]` section of the workspace
- [x] in it create a crate that will contain the utility methods, mostly wrappers around `starknet-rs`
- [x] create a test file by RPC route and fill it with our new tests
- [x] remove js tests and clean up the related tooling

## Required lib functionalities
- [x] send rpc call
- [x] send Txs
- [x] seal block
- [x] jump N blocks

### Skiped RPC routes
- syncing

### Special cases

> Starknet currently supports calls about a [pending block](https://docs.starknet.io/documentation/architecture_and_concepts/Blocks/transaction-life-cycle/#the_pending_block), the block being built. Madara doesn't, so any request about `BlockId::Tag(BlockTag::Pending))` should return an error 

### Routes to test

<details>
<summary>blockNumber</summary>

#### Rust impl
```rust
fn block_number(&self) -> RpcResult<u64>;
```

#### Things to test
- [x] Return 0 at block 0
- [x] Return the correct block number after creating 1, 10, 100, 1000, 1,000,000 (only if it does not take too long to execute) empty blocks
</details>

<details>
<summary>blockHashAndNumber</summary>

#### Rust impl
```rust
 fn block_hash_and_number(&self) -> RpcResult<BlockHashAndNumber>;
```

#### Things to test
- [x] Return the correct block number at blocks and hash at block 0
- [x]  Return the correct block number at blocks and hash after an empty block is created
- [x]  Return the correct block number at blocks and hash after diverse blocks with diverse tx are created
</details>

<details>
<summary>getBlockTransactionCount</summary>
#### Rust impl
```rust
fn get_block_transaction_count(&self, block_id: BlockId) -> RpcResult<u128>;
```

#### Things to test
- [x] Return the correct number of tx for empty blocks
- [x]  Return the correct number of tx in a block with multiple tx
- [x] Return an error for a nonexisting block
</details>

<details>
<summary>getStorageAt</summary>

#### Rust impl

```rust
fn get_storage_at(&self, contract_address: FieldElement, key: FieldElement, block_id: BlockId) -> RpcResult<Felt>;
```

#### Things to test
- [x] Return an error for a nonexisting block
- [x] Return an error for a non-existing contract
- [x] Return an error for a non-existing key in an existing contract
- [x]  Return the correct value previously stored in a contract
</details>

<details>
<summary>call</summary>

#### Rust impl

```rust
fn call(&self, request: FunctionCall, block_id: BlockId) -> RpcResult<Vec<String>>;
```

#### Things to test
- [x] Return an error for a nonexisting block
- [x] Return an error for a nonexisting `FunctionCall`'s `contract_address` or `entry_point_selector` and for an invalid `calldata`
- [x] Otherwise, return an execution result 
- [x] storage should not be updated, even when successfully calling a method that usually does. It should be a dry run.
</details>

<details>
<summary>getClassAt</summary>

#### Rust impl

```rust
 fn get_class_at(&self, block_id: BlockId, contract_address: FieldElement) -> RpcResult<ContractClass>;
```

#### Things to test
- [x] Return an error for a nonexisting block
- [x] Return an error for an address that has not contract deployed
- [x] Otherwise, return the `ContractClass` of the contract that was deployed at this address 
</details>

<details>
<summary>getClassHashAt</summary>

#### Rust impl

```rust
fn get_class_hash_at(&self, block_id: BlockId, contract_address: FieldElement) -> RpcResult<Felt>;
```

#### Things to test
- [x] Return an error for a nonexisting block
- [x] Return an error for an address that has not contract deployed
- [x] Otherwise, return the hash of the `ContractClass` of the contract that was deployed at this address 
</details>

<details>
<summary>getClass</summary>

#### Rust impl

```rust
fn get_class(&self, block_id: BlockId, class_hash: FieldElement) -> RpcResult<ContractClass>;
```

#### Things to test
- [x] Return an error for a nonexisting block
- [x] Return an error for a hash that matches no previously deployed `ContractClass`
- [x] Otherwise, return the `ContractClass` related to this `class_hash`
</details>

<details>
<summary>getNonce</summary>

#### Rust impl

```rust
fn get_nonce(&self, block_id: BlockId, contract_address: FieldElement) -> RpcResult<Felt>;
```

#### Things to test
- [x] Return an error for a nonexisting block
- [x] Return an error for a non-used contract address
- [x] Return an error if the contract deployed at this address is not an account contract
- [x] Otherwise, return the nonce of the account deployed at this address
</details>

<details>
<summary>getBlockWithTxHashes</summary>

#### Rust impl

```rust
fn get_block_with_tx_hashes(&self, block_id: BlockId) -> RpcResult<MaybePendingBlockWithTxHashes>;
```

#### Things to test
- [x] Return an error for a nonexisting block
- [x] Return the `BlockWithTxHashes` object. Check that each field in the struct is valid. Including the hash of the tx that were executed.
</details>

<details>
<summary>getBlockWithTxs</summary>

#### Rust impl

```rust
 fn get_block_with_txs(&self, block_id: BlockId) -> RpcResult<MaybePendingBlockWithTxs>;
```

#### Things to test
- [x] Return an error for a nonexisting block
- [x] Return the `BlockWithTxs` object. Check that each field in the struct is valid. And all transactions are included.
</details>

<details>
<summary>chainId</summary>

#### Rust impl

```rust
fn chain_id(&self) -> RpcResult<Felt>;
```

#### Things to test
- [x] Return the value we hardcoded as chainId. 
</details>

<details>
<summary>addInvokeTransaction</summary>

#### Rust impl

```rust
async fn add_invoke_transaction(&self, invoke_transaction: BroadcastedInvokeTransaction) -> RpcResult<InvokeTransactionResult>;
```

#### Things to test
- [x] Return the hash of the transaction if it was valid, error if it failed during verification

After sealing the block:
- [x] the tx has been included in the block if the tx was successful
- [x] the state has been updated if the tx was successful
- [x] the tx has not been included in the block if the tx was refused
- [x] the state has not been updated if the tx was refused 
</details>

<details>
<summary>addDeployAccountTransaction</summary>

#### Rust impl

```rust
async fn add_deploy_account_transaction(&self, deploy_account_transaction: BroadcastedDeployAccountTransaction) -> RpcResult<DeployAccountTransactionResult>;
```

#### Things to test
- [x] Return the hash of the transaction and the account address if it was valid, error if it failed

After sealing the block:
- [x] the tx is in the block
- [x] a new account contract exists at this address
- [x] none of this if the tx failed
</details>

<details>
<summary>addDeclareTransaction</summary>

#### Rust impl

```rust
async fn add_declare_transaction(&self, declare_transaction: BroadcastedDeclareTransaction) -> RpcResult<DeclareTransactionResult>;
```

#### Things to test
- [x] the tx is in the block
- [x] a new ContractClass is present in the storage
- [x] none of this if the tx failed
- [x] Tx fails if the ContractClass is already declared
</details>

<details>
<summary>estimateFee</summary>

#### Rust impl

```rust
async fn estimate_fee(&self, request: Vec<BroadcastedTransaction>, block_id: BlockId) -> RpcResult<Vec<FeeEstimate>>;
```

#### Things to test
- [ ] Return an error for a nonexisting block
- [ ] Return an error if one of the tx cannot be executed
- [ ] Return a vec of fees of the same length as the one in `request`
- [ ] fee estimation is coherent (???)
</details>

<details>
<summary>getTransactionByBlockIdAndIndex</summary>

#### Rust impl

```rust
fn get_transaction_by_block_id_and_index(&self, block_id: BlockId, index: usize) -> RpcResult<Transaction>;
```

#### Things to test
- [x] Return an error for a nonexisting block
- [x] Return an error for an out of block index
- [x] Compare with getBlockWithTx and make sure order is the same
</details>

<details>
<summary>getStateUpdate</summary>

#### Rust impl

```rust
 fn get_state_update(&self, block_id: BlockId) -> RpcResult<StateUpdate>;
```

#### Things to test
- [ ] Return an error for a nonexisting block
- [ ] Otherwise, return the block state update
- [ ] Check that the state diff is valid given the tx executed in the block
- [ ] Check that the `block_hash` and `old_root` are correct
</details>

<details>
<summary>pendingTransactions</summary>

#### Rust impl

```rust
async fn pending_transactions(&self) -> RpcResult<Vec<Transaction>>;
```

#### Things to test
- [x] Call RPC to add TXs, don't seal the block, call `pendingTransactions`, check that the transactions you added are returned
</details>

<details>
<summary>getEvents</summary>

#### Rust impl

```rust
async fn get_events(&self, filter: EventFilterWithPage) -> RpcResult<EventsPage>;
```

#### Things to test
There are already unit tests on the filter mechanism so we can go light here.
Just test a few combinations of bound, address, and keys
</details>

<details>
<summary>getTransactionByHash</summary>

#### Rust impl

```rust
fn get_transaction_by_hash(&self, transaction_hash: FieldElement) -> RpcResult<Transaction>;
```

#### Things to test
- [x] Return an error if there is not tx with this hash in the chain
- [x] Return the Tx if there is one matching the hash
</details>

<details>
<summary>getTransactionReceipt</summary>

#### Rust impl

```rust
fn get_transaction_receipt(&self, transaction_hash: FieldElement) -> RpcResult<MaybePendingTransactionReceipt>;
```

#### Things to test
- [x] Return an error if there is not tx with this hash in the chain
- [x] Return the TxReceipt if there is one matching the hash
</details>

**Comment by tdelabro** [comment]
I think the integration tests should cover all of our RPC endpoints. With one or more variations for each RPC.
For calling the RPC, we could use [starknet-rs](https://github.com/xJonathanLEI/starknet-rs) directly.

We would also love to have the ability to load as a specific state of the Starknet chain, then execute the next N blocks and make sure we end up with the exact same state.
Maybe we could use try-runtime for this. I saw there some work has already be done in this direction in https://github.com/keep-starknet-strange/madara/pull/690

**Comment by xJonathanLEI** [comment]
Great initiative! My only concern with this is then we're then essentially circle jerking lol, at least on the RPC layer, since Madara uses `starknet-rs` for that.

**Comment by tdelabro** [comment]
Yes, we have been discussing it internally and @LucasLvy raised the exact same point.

Our position is that it's not our role (understand "main focus") to test starknet-rs (even if we would be glad to help find a bug). We trust our dependencies to do their job. In this specific situation, we trust starknet-rs with the Ser/De of the struct defined by Starknet in their openRPC. And yes, we won't be aware if you deviate from this standard.

We instead want to test our own code. Meaning from the moment we have the deserialized call data struct until we serialize the answer. This includes our RPC logic, our custom storage, our interface with the runtime, our custom way to read directly into the storage, and all of our extrinsic from the moment we enter the runtime to the moment we give the data to the Blockifier (and back).

Is it an understandable approach in your opinion?

**Comment by ptisserand** [comment]
Hi, can I work on `getClassAt` and `getClassHashAt` ?

**Comment by tdelabro** [comment]
Sure !

**Comment by tdelabro** [comment]
@EvolveArt are you working on some yourself?

**Comment by apoorvsadana** [comment]
Hey, I will work on `call` to start with. Will try to pick more after I implement this one.

**Comment by tchataigner** [comment]
Hey ! I am keen to grab `getNonce` as a first PR and work on others later on !

**Comment by ptisserand** [comment]
Hey, I would like to grab `getClass`

**Comment by apoorvsadana** [comment]
I will pick up `getBlockWithTxHashes` and `getBlockWithTxs`

**Comment by 0xAsten** [comment]
Hi, I will try out `blockNumber` and `blockHashAndNumber`.

**Comment by apoorvsadana** [comment]
I will do `addInvokeTransaction `, `addDeployAccountTransaction` and `addDeclareTransaction`

**Comment by apoorvsadana** [comment]
Is there any reason why the test cases are not inside the `src` folder?

**Comment by kasteph** [comment]
I'll give `getStateUpdate` a try.

**Comment by tdelabro** [comment]
> Why are the test cases not inside the src folder?

My reasoning was that they don't actually tests the lib they belong to.
There are more tests that require this lib to work.

**Comment by apoorvsadana** [comment]
got it, makes sense @tdelabro. thanks!

**Comment by apoorvsadana** [comment]
I will do `pendingTransactions` and `getTransactionByHash`

**Comment by apoorvsadana** [comment]
will also finish `getEvents` and `getTransactionReceipt`

**Comment by tdelabro** [comment]
I created two issues for the last ones: #1150 and #1151

At the same time I'm working on making all the rpc tests run on a single node, instead of each one spawning it's node. It should greatly improve the time taken to run the CI
